export const errorCodes = {
    INTERNAL: "INTERNAL_ERROR",
    VALIDATION: "VALIDATION_ERROR",
    BAD_REQUEST: "BAD_REQUEST",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    NOT_FOUND: "NOT_FOUND",
    CONFLICT: "CONFLICT",
    RATE_LIMITED: "RATE_LIMITED",
    ACCOUNT_TEMP_LIMITED: "ACCOUNT_TEMP_LIMITED",
    QUOTA_EXCEEDED: "QUOTA_EXCEEDED",
    PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
    UPSTREAM_ERROR: "UPSTREAM_ERROR",
    UPSTREAM_UNAVAILABLE: "UPSTREAM_UNAVAILABLE",
    UPSTREAM_TIMEOUT: "UPSTREAM_TIMEOUT",
} as const;

export type ErrorCode = (typeof errorCodes)[keyof typeof errorCodes];
